# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provision :shell, :path => "install-elasticsearch.sh", :args => ["-n", "es-azure"]
  config.vm.network :forwarded_port, guest: 9200, host: 9200
end
